name: carmarketapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  syncfusion_flutter_gauges: ^24.1.43
  flutter_svg: ^2.0.9
  cached_network_image: ^3.1.0
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.3.5
  provider: ^6.1.2
  country_picker: ^2.0.27
  scroll_snap_list: ^0.9.1
  file_picker: ^9.0.1
  path_provider: ^2.1.5
  http: ^0.13.1
  path: ^1.9.0
  shimmer: ^3.0.0
  fancy_shimmer_image: ^2.0.3
  auto_size_text: ^3.0.0
  flutter_spinkit: ^5.2.0
  url_launcher: ^6.3.1
  lottie: ^2.3.0
  sqflite: ^2.4.1
  internet_connection_checker: ^0.0.1+3
  phone_numbers_parser: ^9.0.3
  fl_chart: ^0.69.0
  flutter_slidable: ^3.1.1
  flutter_custom_clippers: ^2.1.0
  flutter_stripe: ^9.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Pippins
      fonts:
        - asset: assets/Fonts/Poppins-Bold.ttf
        - asset: assets/Fonts/Poppins-Medium.ttf
        - asset: assets/Fonts/Poppins-Regular.ttf

flutter_native_splash:
  color: "#222831"
  image: assets/images/car4sale.png

  android_12:
    image: assets/images/car4sale.png
    icon_background_color: "#222831"

  android: true
  ios: true
  fullscreen: true

